import { StyleSheet } from 'react-native';
import { RFPercentage, RFValue } from 'react-native-responsive-fontsize';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
  },
  visor: {
    borderRadius: 20,
    // borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    top: '20%',
    // padding: '2%'
    width: '100%',
    minHeight: 80,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  number: {
    color: 'white',
    fontSize: RFPercentage(10),
    textAlign: 'right',
  },
  grid: {
    borderRadius: 20,
    borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '95%',
    marginTop: '50%',
    height: '60%',
  },
  gridL1: {
    borderRadius: 20,
    borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '100%',
    marginTop: '0%',
    height: '20%',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: '1%',
  },
  gridL2: {
    borderRadius: 20,
    borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '100%',
    marginTop: '0%',
    height: '20%',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: '1%',
  },
  gridL3: {
    borderRadius: 20,
    borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '100%',
    marginTop: '0%',
    height: '20%',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: '1%',
  },
  gridL4: {
    borderRadius: 20,
    borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '100%',
    marginTop: '0%',
    height: '20%',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: '1%',
  },
  gridL5: {
    borderRadius: 20,
    borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '100%',
    marginTop: '0%',
    height: '20%',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: '1%',
  },
  botoes: {
    borderRadius: '50%',
    // borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '25%',
    height: '90%',
    backgroundColor: '#111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botoesLine1: {
    borderRadius: '50%',
    // borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '25%',
    height: '90%',
    backgroundColor: '#666',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botoesColumn4: {
    borderRadius: '50%',
    // borderWidth: RFPercentage(0.1),
    // borderColor: 'white',
    width: '25%',
    height: '90%',
    backgroundColor: '#f70',
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtBotoes: {
    fontSize: RFPercentage(4.5),
    color: '#fff',
  },
});

export default styles;
